vpc_cidr_block       = "10.0.0.0/16"
subnet_cidr_block    = "10.0.10.0/24"
availability_zone    = "us-east-1a"
env_prefix           = "dev"
instance_type        = "t2.micro"
public_key_location  = "C:/Users/USER/.ssh/id_rsa.pub"
private_key_location = "C:/Users/USER/.ssh/id_rsa"
my_ip                = "80.89.77.167/32"